---
- name: installing packages on different operating systems
  hosts: all
  become: true
  gather_facts: yes

  tasks:
  - name: install httpd
    yum:
      name: httpd
      state: present
    when: ansible_os_family == "RedHat"
  
  - name: install apache2
    apt:
      name: apache2
      state: present
    when: ansible_os_family == "Debian"
  
  - name: start httpd
    service:
      name: httpd
      state: started
    when: ansible_os_family == "RedHat"
  
  - name: start apache2
    service:
      name: apache2
      state: started
    when: ansible_os_family == "Debian"