---
- name: create file
  hosts: all
  become: true
  gather_facts: no
  tasks:
    - name: create hello file
      file:
        path: ~/hello
        state: touch
        mode: 0744
    - name: create directory
      file:
        path: /satya/sai
        state: directory
        mode: 0744
        