- name: install package
  hosts: all
  become: true
  gather_facts: no
  tasks:
    - name: install httpd
      yum:
        name: httpd
        state: present
    - name: start httpd
      service:
        name: httpd
        state: started
    - name: copy index.html to remote
      copy:
        src: index.html
        dest: /var/www/html
      
