---
- name: installing packages on different operating systems
  hosts: all
  become: true
  gather_facts: yes

  tasks:
  - name: install httpd
    yum:
      name: httpd
      state: present
    when: ansible_os_family == "RedHat"
    notify: start httpd
  
  - name: install apache2
    apt:
      name: apache2
      state: present
    when: ansible_os_family == "Debian"
    notify: start apache2
  
  - name: copy index.html to remote
    copy:
      src: index.html
      dest: /var/www/html

  handlers:
  - name: start httpd
    service:
      name: httpd
      state: started
      enabled: true
  
  - name: start apache2
    service:
      name: apache2
      state: started
      enabled: true